#!/usr/bin/env bash
# Live smart-money loop — maximum cash deployment, smart trades only, no noise.
# Sizing: % of available cash × conviction multiplier.
# Aggressive deployment (75% of cash per trade), strict signal quality.
set -euo pipefail

cd "$(dirname "$0")/.."

export POLYMARKET_ENABLE_LIVE_TRADING=1
export POLYMARKET_SYNC_LIVE_POSITIONS=1

# ── Trader quality ──
export POLYMARKET_SMART_MIN_TRADER_PNL=2000

# ── Scan scope ──
export POLYMARKET_SMART_CATEGORIES=OVERALL,FINANCE,ECONOMICS,TECH,POLITICS,SPORTS,CULTURE,WEATHER
export POLYMARKET_SMART_DISCOVERY_KEYWORDS='election,trump,senate,congress,fed,inflation,cpi,unemployment,gdp,weather,rain,snow,hurricane,temperature,box office,movie,earnings,stock,nasdaq'
export POLYMARKET_SMART_TIME_PERIOD=MONTH
export POLYMARKET_SMART_LEADERBOARD_LIMIT=100

# ── Crypto (only high-conviction) ──
export POLYMARKET_SMART_ALLOW_CRYPTO=1
export POLYMARKET_SMART_CRYPTO_MIN_BUY_PRICE=0.70
export POLYMARKET_SMART_CRYPTO_MIN_HOURS_TO_CLOSE=2
export POLYMARKET_SMART_CRYPTO_MAX_HOURS_TO_CLOSE=48
export POLYMARKET_SMART_CRYPTO_MIN_COPIED_USDC=1500

# ── Sizing (aggressive: 75% of cash × conviction, 50% equity ceiling) ──
export POLYMARKET_SMART_POSITION_PCT=0.75
export POLYMARKET_SMART_MAX_POSITION_CEILING_USD=150
export POLYMARKET_SMART_MAX_POSITION_CEILING_PCT=0.50
export POLYMARKET_SMART_HIGH_CONVICTION_BALANCE_FRACTION=0.80
export POLYMARKET_SMART_CASH_FLOOR_PCT=0.05

# ── Signal freshness & consensus ──
export POLYMARKET_SMART_MIN_CONSENSUS=2
export POLYMARKET_SMART_FALLBACK_CONSENSUS=2
export POLYMARKET_SMART_TRADE_LOOKBACK_MINUTES=120
export POLYMARKET_SMART_MAX_SIGNAL_AGE_MINUTES=5
export POLYMARKET_SMART_MIN_COPIED_USDC=125
export POLYMARKET_SMART_MAX_CHASE_PREMIUM=0.08
export POLYMARKET_SMART_MAX_ENTRY_SLIPPAGE=0.08
export POLYMARKET_SMART_MIN_BUY_PRICE=0.05
export POLYMARKET_SMART_MAX_BUY_PRICE=0.92
export POLYMARKET_SMART_MAX_SPREAD=0.06

# ── More smart signals via relaxed fallback passes ──
export POLYMARKET_SMART_DEEP_FALLBACK_ENABLED=1
export POLYMARKET_SMART_DEEP_FALLBACK_MIN_COPIED_USDC=25
export POLYMARKET_SMART_CASH_PRESSURE_ENABLED=1
export POLYMARKET_SMART_CASH_PRESSURE_MIN_CASH_PCT=0.15
export POLYMARKET_SMART_CASH_PRESSURE_MIN_COPIED_USDC=10
export POLYMARKET_SMART_CASH_PRESSURE_MAX_SIGNAL_AGE_MINUTES=60
export POLYMARKET_SMART_CASH_PRESSURE_MAX_RELATIVE_SPREAD=0.75

# ── Category scores ──
export POLYMARKET_SMART_PRIORITY_CATEGORY_BONUS=8
export POLYMARKET_SMART_SPORTS_SCORE_PENALTY=12
export POLYMARKET_SMART_MAX_SPORTS_POSITIONS=2

# ── Market horizon ──
export POLYMARKET_SMART_SOON_HOURS=168
export POLYMARKET_SMART_MIN_HOURS_TO_CLOSE=1
export POLYMARKET_SMART_MAX_HOURS_TO_CLOSE=48

# ── Exit strategy ──
export POLYMARKET_SMART_TAKE_PROFIT_TIERS=1.0:0.50,2.0:0.25,3.0:0.15
export POLYMARKET_SMART_PEAK_PROTECT_TRIGGER=1.0
export POLYMARKET_SMART_PEAK_PROTECT_FLOOR=0.40
export POLYMARKET_SMART_STOP_LOSS_PCT=0.40
export POLYMARKET_SMART_STOP_LOSS_MIN_AGE_MINUTES=15
export POLYMARKET_SMART_COHORT_EXIT_ENABLED=1
export POLYMARKET_SMART_COHORT_EXIT_LOOKBACK_MINUTES=120
export POLYMARKET_SMART_COHORT_EXIT_MIN_AGE_MINUTES=20
export POLYMARKET_SMART_EXIT_MINUTES_TO_CLOSE=20
export POLYMARKET_SMART_EXIT_MIN_PROFIT=0.05

# ── Loop ──
export POLYMARKET_AUTO_INTERVAL_SECONDS=20

if command -v uv >/dev/null 2>&1; then
    exec uv run pmbot auto-loop
fi

if [ -f .venv/bin/python ]; then
    exec .venv/bin/python -B -m polymarket_bot.main auto-loop
fi

exec python3 -B -m polymarket_bot.main auto-loop
