#!/usr/bin/env bash
# Live smart-money loop tuned for a ~$90 bankroll.
# Bigger per-trade size, more concurrent positions, slightly looser entry filters.
# All safety nets stay on: stop-loss, cohort-sell exit, peak-protect, take-profit ladder.
# Run: bash scripts/run_live_70.sh

set -euo pipefail

cd "$(dirname "$0")/.."

export POLYMARKET_ENABLE_LIVE_TRADING=1
export POLYMARKET_SYNC_LIVE_POSITIONS=1
export POLYMARKET_ASSUME_LIVE_BALANCE_USD=90

export POLYMARKET_SMART_CATEGORIES=OVERALL,FINANCE,ECONOMICS,TECH,POLITICS,SPORTS,CULTURE,WEATHER
export POLYMARKET_SMART_DISCOVERY_KEYWORDS='election,trump,senate,congress,fed,inflation,cpi,unemployment,gdp,weather,rain,snow,hurricane,temperature,box office,movie,earnings,stock,nasdaq'
export POLYMARKET_SMART_TIME_PERIOD=MONTH
export POLYMARKET_SMART_LEADERBOARD_LIMIT=100
export POLYMARKET_SMART_MIN_TRADER_PNL=2000
export POLYMARKET_SMART_MIN_TRADER_VOLUME=5000
export POLYMARKET_SMART_MIN_TRADER_ROI=0.05
export POLYMARKET_SMART_TRADE_FETCH_CONCURRENCY=16
export POLYMARKET_SMART_REVERSE_LOOKUP_ENABLED=1
export POLYMARKET_SMART_REVERSE_LOOKUP_MAX_TOKENS=30
export POLYMARKET_SMART_REVERSE_LOOKUP_MIN_COPIED_USDC=100

export POLYMARKET_SMART_ALLOW_CRYPTO=1
export POLYMARKET_SMART_CRYPTO_MIN_BUY_PRICE=0.70
export POLYMARKET_SMART_CRYPTO_MIN_HOURS_TO_CLOSE=2
export POLYMARKET_SMART_CRYPTO_MAX_HOURS_TO_CLOSE=48
export POLYMARKET_SMART_CRYPTO_MIN_COPIED_USDC=1500

export POLYMARKET_MAX_POSITION_USD=7
export POLYMARKET_SMART_MAX_TRADE_USD=7
export POLYMARKET_SMART_HIGH_CONVICTION_BALANCE_FRACTION=0.15
export POLYMARKET_SMART_POSITION_PCT=0.10
export POLYMARKET_SMART_MAX_POSITION_CEILING_USD=75

export POLYMARKET_SMART_MIN_CONSENSUS=2
export POLYMARKET_SMART_FALLBACK_CONSENSUS=2
export POLYMARKET_MIN_OPEN_POSITIONS=7
export POLYMARKET_SMART_DEEP_FALLBACK_ENABLED=1
export POLYMARKET_SMART_DEEP_FALLBACK_MIN_COPIED_USDC=100
export POLYMARKET_SMART_TRADE_LOOKBACK_MINUTES=30
export POLYMARKET_SMART_MAX_SIGNAL_AGE_MINUTES=10

export POLYMARKET_SMART_MIN_TRADE_USD=1
export POLYMARKET_SMART_MIN_COPIED_USDC=75
export POLYMARKET_SMART_MAX_CHASE_PREMIUM=0.13
export POLYMARKET_SMART_MAX_ENTRY_SLIPPAGE=0.12

export POLYMARKET_SMART_PRIORITY_CATEGORY_BONUS=8
export POLYMARKET_SMART_SPORTS_SCORE_PENALTY=12
export POLYMARKET_SMART_MAX_SPORTS_POSITIONS=3

export POLYMARKET_SMART_SOON_HOURS=168
export POLYMARKET_SMART_MIN_HOURS_TO_CLOSE=1
export POLYMARKET_SMART_MAX_HOURS_TO_CLOSE=72

export POLYMARKET_SMART_MIN_BUY_PRICE=0.03
export POLYMARKET_SMART_MAX_BUY_PRICE=0.96
export POLYMARKET_SMART_MAX_SPREAD=0.08
export POLYMARKET_SMART_MAX_RELATIVE_SPREAD=0.45

export POLYMARKET_SMART_TAKE_PROFIT_TIERS=1.0:0.50,2.0:0.25,3.0:0.15
export POLYMARKET_SMART_PEAK_PROTECT_TRIGGER=1.0
export POLYMARKET_SMART_PEAK_PROTECT_FLOOR=0.40
export POLYMARKET_SMART_TRAILING_STOP_ARM_PCT=0.25
export POLYMARKET_SMART_TRAILING_STOP_GIVEBACK_PCT=0.50
export POLYMARKET_SMART_STOP_LOSS_PCT=0.40
export POLYMARKET_SMART_STOP_LOSS_MIN_AGE_MINUTES=15
export POLYMARKET_SMART_COHORT_EXIT_ENABLED=1
export POLYMARKET_SMART_COHORT_EXIT_LOOKBACK_MINUTES=120
export POLYMARKET_SMART_COHORT_EXIT_MIN_AGE_MINUTES=20
export POLYMARKET_SMART_COHORT_EXIT_MIN_WALLETS=2
export POLYMARKET_SMART_EXIT_MINUTES_TO_CLOSE=20
export POLYMARKET_SMART_EXIT_MIN_PROFIT=0.05

export POLYMARKET_AUTO_INTERVAL_SECONDS=20

exec python3 -B -m polymarket_bot.main auto-loop
