#!/usr/bin/env bash
# Live smart-money loop — pure code defaults, same as Pierre's setup.
# Run: bash scripts/run_live_70.sh
set -euo pipefail

cd "$(dirname "$0")/.."

export POLYMARKET_ENABLE_LIVE_TRADING=1
export POLYMARKET_SYNC_LIVE_POSITIONS=1
export POLYMARKET_ASSUME_LIVE_BALANCE_USD=150

# Override any .env restrictive values back to code defaults
export POLYMARKET_SMART_MIN_TRADER_PNL=0
export POLYMARKET_SMART_MIN_TRADER_VOLUME=0
export POLYMARKET_SMART_MIN_TRADER_ROI=0
export POLYMARKET_SMART_MIN_CONSENSUS=2
export POLYMARKET_SMART_MIN_COPIED_USDC=5
export POLYMARKET_SMART_TRADE_LOOKBACK_MINUTES=1440
export POLYMARKET_SMART_MAX_SIGNAL_AGE_MINUTES=0
export POLYMARKET_SMART_MAX_SPREAD=0.25
export POLYMARKET_SMART_MAX_CHASE_PREMIUM=0.35
export POLYMARKET_SMART_MAX_ENTRY_SLIPPAGE=0.50
export POLYMARKET_SMART_MIN_BUY_PRICE=0.02
export POLYMARKET_SMART_MAX_BUY_PRICE=0.98
export POLYMARKET_SMART_SOON_HOURS=72
export POLYMARKET_SMART_MIN_HOURS_TO_CLOSE=0.10
export POLYMARKET_SMART_MAX_HOURS_TO_CLOSE=168
export POLYMARKET_SMART_CASH_FLOOR_PCT=0.02
export POLYMARKET_SMART_POSITION_PCT=0.50
export POLYMARKET_SMART_MAX_POSITION_CEILING_USD=150
export POLYMARKET_SMART_MAX_POSITION_CEILING_PCT=0.40
export POLYMARKET_SMART_SPORTS_SCORE_PENALTY=4
export POLYMARKET_SMART_MAX_SPORTS_POSITIONS=8

exec uv run pmbot auto-loop
